[quote.epigraph, , Psalm 92:13-14]
____
They that be planted in the house of the Lord, shall flourish in the courts of our God; they shall still bring forth fruit in old age—they shall be fat and flourishing.
____

== Introduction.

The desire to contribute to the promotion of the cause of practical religion,
and to hold out the language of encouragement or admonition to
those who should succeed him in the Christian pilgrimage,
appear to have been the motives which induced our late beloved and honoured Friend,
Henry Hull, to preserve some memorandums of his life,
and of those conflicts and exercises, as well as joys and consolations,
which he passed through,
in the course of the great work of redemption from the bondage of sin,
and preparation for the service of his gracious Lord and Saviour.

He possessed a sound and discriminating mind,
whose faculties had been enlarged and strengthened by a
long course of discipline in the school of Christ;
and though he had but little opportunity of acquiring human learning,
and his manner of writing is not, therefore, what the world calls polished,
yet the want of this is far outbalanced by the religious
instruction with which the journal is fraught,
imparting to it an attraction superior to the embellishments of style.
Several years before his decease, he exhibited the manuscripts to one of the editors,
and with his characteristic diffidence and humility,
expressed his sense of their defectiveness, and also intimated his wish,
that if his friends who survived him, thought they would be useful,
he would put them in a form suitable for publication.
In performing this duty to a dear departed friend, necessary corrections have been made,
and some uninteresting matter omitted;
but care has been taken to preserve the meaning of the author.
It is to be regretted that there are some chasms in his narrative,
which we have not the means of supplying,
although considerable pains have been taken to procure materials for it.
All that can now be done toward remedying these deficiencies,
is a simple statement of the religious engagements in
which he was employed during those periods.

Religious biography is a fruitful source of instruction
and encouragement to the Christian traveller.
It is interesting to trace the various steps by which those servants of Christ,
who have gone before us,
have been led through the vicissitudes and trials of this changeful life,
to everlasting blessedness and glory.
The record of their experience bears witness,
that by yielding to the tendering visitations of the love of God,
which seeks to gather all into the fold of rest and peace,
and to those baptisms of the Holy Spirit,
which humble the pride and loftiness of the human heart and
bring the whole man into obedience to the law of Christ,
they were fitted for service in the church and made instruments of good unto others.
These gracious visitations of heavenly love are, at seasons, tendered to every soul,
in order to bring it out of the bondage of corruption,
and translate it into the glorious liberty of the children of God;
and it is only by surrendering the whole heart to their transforming power,
that we can experience the blessed fruits of the Spirit brought forth in us,
and thus be prepared to labour availingly for the advancement
of the kingdom of our dear Redeemer in the earth.

The "`power from on high`" has endued the righteous of all ages with wisdom
and ability for the work of their day--supported and consoled them amid the
afflictions and trials incident to this imperfect state of being;
enabled them to persevere in their heavenly
journey with holy stability and circumspection,
to meet with Christian fortitude and resignation,
every dispensation of an all-wise Providence,
and at last to finish their course with joy; trusting not in their own righteousness,
but in the pardon, reconciliation and mercy which are in Christ Jesus our Lord.
This Divine power and spirit remains unchanged to the present day,
and is freely offered for the help of all those who
love and serve the Lord in uprightness of heart;
his gracious words being still in full force, "`Lo I am with you always,
even unto the end of the world.`"

When we contemplate the happy effects which it wrought in those devoted servants,
who have fallen asleep in Jesus--their work of faith and labour of love--their
patience under suffering--their humility and gentleness-- their meek and cheerful
submission to the will of God--their unwearied devotion to his cause,
and their holy hope, full of immortality and eternal life, in the near prospect of death;
how does it animate the soul to press after the attainment of the same Christian virtues,
and through the aid of the Holy Spirit, to "`follow them as they followed Christ.`"

"`The harvest truly is great and the labourers are few;`" many
who had long "`borne the burden and heat of the day,`" having
of latter years been removed from the militant church,
to join the glorified church triumphant in heaven;
so that the injunction of our blessed Saviour to his disciples,
is peculiarly appropriate at the present time,
"`Pray ye therefore the Lord of the harvest,
to send forth more labourers into his harvest.`"
May the perusal of the following pages incite to a serious examination,
how far we are occupying our time and talents to the honour of the great Giver,
and induce a willingness to bear the yoke and cross of Christ,
and openly acknowledge our allegiance to him before the world;
that through the ability which he dispenses to his obedient children,
we also may serve our generation according to the will of God;
and when our allotted portion of suffering and of service is accomplished, may,
through unmerited mercy, receive the end of our faith, even the salvation of our souls.

[.signed-section-context-close]
Philadelphia, Fourth month 1st, 1840.
